-- V1: reference tables (airports, aircraft). Seed data is in V4.

-- -----------------------------------------------------------------------------
-- Reference data (seeded, read-only)
-- -----------------------------------------------------------------------------

CREATE TABLE airport (
    code        VARCHAR(3)   PRIMARY KEY,                 -- IATA code
    name        VARCHAR(150) NOT NULL,
    city        VARCHAR(100) NOT NULL,
    country     VARCHAR(100) NOT NULL,
    -- PostgreSQL regex; MySQL 8: CHECK (code REGEXP '^[A-Z]{3}$')
    CONSTRAINT chk_airport_code CHECK (code ~ '^[A-Z]{3}$')
);

CREATE TABLE aircraft (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(20) NOT NULL,                 -- e.g. registration
    aircraft_type   VARCHAR(50) NOT NULL,                 -- e.g. A320
    row_count       INTEGER     NOT NULL,
    seat_letters    VARCHAR(12) NOT NULL,                 -- e.g. ABCDEF, in seat-map order
    CONSTRAINT uq_aircraft_code      UNIQUE (code),
    CONSTRAINT chk_aircraft_rows     CHECK (row_count BETWEEN 1 AND 99),
    CONSTRAINT chk_aircraft_letters  CHECK (seat_letters ~ '^[A-Z]+$')
);
