-- V2: schedules (templates) and flight instances (one row per operating date).

-- -----------------------------------------------------------------------------
-- Schedules (templates) and flight instances (materialised, one per date)
-- -----------------------------------------------------------------------------

CREATE TABLE flight_schedule (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flight_number       VARCHAR(8)  NOT NULL,
    origin_code         VARCHAR(3)  NOT NULL REFERENCES airport (code),
    destination_code    VARCHAR(3)  NOT NULL REFERENCES airport (code),
    departure_time      TIME        NOT NULL,             -- UTC time of day
    arrival_time        TIME        NOT NULL,             -- UTC time of day
    -- Derived, never supplied: 1 when arrival_time <= departure_time (overnight).
    arrival_day_offset  INTEGER     NOT NULL DEFAULT 0,
    aircraft_id         BIGINT      NOT NULL REFERENCES aircraft (id),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_schedule_flight_number UNIQUE (flight_number),
    CONSTRAINT chk_schedule_route        CHECK (origin_code <> destination_code),
    CONSTRAINT chk_schedule_day_offset   CHECK (arrival_day_offset BETWEEN 0 AND 1)
);

CREATE TABLE flight_schedule_day (
    schedule_id     BIGINT     NOT NULL REFERENCES flight_schedule (id),
    day_of_week     VARCHAR(9) NOT NULL,
    PRIMARY KEY (schedule_id, day_of_week),
    CONSTRAINT chk_schedule_day CHECK (day_of_week IN
        ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY'))
);

CREATE TABLE flight_instance (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_id         BIGINT      NOT NULL REFERENCES flight_schedule (id),
    -- Route and aircraft are copied from the (immutable) schedule so that
    -- search reads one table through one index.
    flight_number       VARCHAR(8)  NOT NULL,
    origin_code         VARCHAR(3)  NOT NULL REFERENCES airport (code),
    destination_code    VARCHAR(3)  NOT NULL REFERENCES airport (code),
    aircraft_id         BIGINT      NOT NULL REFERENCES aircraft (id),
    flight_date         DATE        NOT NULL,             -- UTC departure date
    departure_at        TIMESTAMPTZ NOT NULL,
    arrival_at          TIMESTAMPTZ NOT NULL,
    total_seats         INTEGER     NOT NULL,
    -- Maintained under the flight row lock: booking/hold decrements,
    -- cancellation/expiry increments.
    available_seats     INTEGER     NOT NULL,
    -- Makes instance generation idempotent (INSERT ... ON CONFLICT DO NOTHING).
    CONSTRAINT uq_instance_schedule_date UNIQUE (schedule_id, flight_date),
    CONSTRAINT chk_instance_seats        CHECK (available_seats BETWEEN 0 AND total_seats),
    CONSTRAINT chk_instance_times        CHECK (arrival_at > departure_at)
);

-- Serves flight search: WHERE origin_code = ? AND destination_code = ? AND flight_date = ?
CREATE INDEX idx_instance_search
    ON flight_instance (origin_code, destination_code, flight_date);
