-- V3: bookings and booked seats. HELD/EXPIRED support the optional seat hold
-- (airline.seat-hold.enabled); with it off only CONFIRMED/CANCELLED and ACTIVE/RELEASED occur.

-- -----------------------------------------------------------------------------
-- Bookings
-- -----------------------------------------------------------------------------

CREATE TABLE booking (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference           VARCHAR(12) NOT NULL,             -- customer-facing PNR
    flight_instance_id  BIGINT      NOT NULL REFERENCES flight_instance (id),
    -- HELD and EXPIRED occur only when airline.seat-hold.enabled = true.
    status              VARCHAR(16) NOT NULL,
    passenger_count     INTEGER     NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL,
    hold_expires_at     TIMESTAMPTZ,                      -- set only while HELD
    cancelled_at        TIMESTAMPTZ,
    -- Serves lookup, confirm and cancel by reference.
    CONSTRAINT uq_booking_reference  UNIQUE (reference),
    CONSTRAINT chk_booking_status    CHECK (status IN ('HELD', 'CONFIRMED', 'CANCELLED', 'EXPIRED')),
    CONSTRAINT chk_booking_count     CHECK (passenger_count > 0)
);

-- Serves lazy hold expiry: HELD bookings on one instance with hold_expires_at <= now.
CREATE INDEX idx_booking_instance ON booking (flight_instance_id);

CREATE TABLE booking_seat (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id          BIGINT       NOT NULL REFERENCES booking (id),
    -- Redundant with booking.flight_instance_id, but needed by uq_active_seat.
    flight_instance_id  BIGINT       NOT NULL REFERENCES flight_instance (id),
    seat_number         VARCHAR(4)   NOT NULL,            -- e.g. 12A
    passenger_name      VARCHAR(120) NOT NULL,
    status              VARCHAR(16)  NOT NULL,
    created_at          TIMESTAMPTZ  NOT NULL,
    released_at         TIMESTAMPTZ,
    CONSTRAINT chk_booking_seat_status CHECK (status IN ('ACTIVE', 'HELD', 'RELEASED'))
);

-- The double-booking guarantee: at most one ACTIVE or HELD row per seat per flight.
-- Also serves the seat map and the availability check
-- (WHERE flight_instance_id = ? AND status IN ('ACTIVE','HELD') [AND seat_number IN (...)]).
--
-- PostgreSQL partial index. MySQL has no partial indexes; the same guarantee there is a
-- nullable column active_seat_key = CONCAT(flight_instance_id, ':', seat_number), set while
-- the seat is ACTIVE or HELD and NULL once RELEASED, with a plain UNIQUE index on it
-- (MySQL unique indexes allow many NULLs).
CREATE UNIQUE INDEX uq_active_seat
    ON booking_seat (flight_instance_id, seat_number)
    WHERE status IN ('ACTIVE', 'HELD');

-- Serves loading a booking's seats (Booking -> BookingSeat collection).
CREATE INDEX idx_booking_seat_booking ON booking_seat (booking_id);
