-- =============================================================================
-- Airline reservation system: consolidated schema (PostgreSQL 16)
--
-- The executable source of truth is db/migrations (Flyway); this file is the same
-- DDL in one place, with comments, for reading. Seed data (airports, aircraft)
-- lives in its own migration and is not repeated here.
--
-- Verified identical to a database migrated with V1-V4: `pg_dump --schema-only`
-- of both gives the same tables, constraints and indexes. (A raw pg_dump is not
-- used as this file because it drops the comments below.)
--
-- PostgreSQL-specific features used (each commented where it appears):
--   * partial unique index        (uq_active_seat)
--   * regular-expression CHECKs   (~ operator)
--   * INSERT ... ON CONFLICT      (used by the instance generator, not DDL)
-- =============================================================================


-- -----------------------------------------------------------------------------
-- Reference data (seeded, read-only)
-- -----------------------------------------------------------------------------

CREATE TABLE airport (
    code        VARCHAR(3)   PRIMARY KEY,                 -- IATA code
    name        VARCHAR(150) NOT NULL,
    city        VARCHAR(100) NOT NULL,
    country     VARCHAR(100) NOT NULL,
    -- PostgreSQL regex; MySQL 8: CHECK (code REGEXP '^[A-Z]{3}$')
    CONSTRAINT chk_airport_code CHECK (code ~ '^[A-Z]{3}$')
);

CREATE TABLE aircraft (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(20) NOT NULL,                 -- e.g. registration
    aircraft_type   VARCHAR(50) NOT NULL,                 -- e.g. A320
    row_count       INTEGER     NOT NULL,
    seat_letters    VARCHAR(12) NOT NULL,                 -- e.g. ABCDEF, in seat-map order
    CONSTRAINT uq_aircraft_code      UNIQUE (code),
    CONSTRAINT chk_aircraft_rows     CHECK (row_count BETWEEN 1 AND 99),
    CONSTRAINT chk_aircraft_letters  CHECK (seat_letters ~ '^[A-Z]+$')
);


-- -----------------------------------------------------------------------------
-- Schedules (templates) and flight instances (materialised, one per date)
-- -----------------------------------------------------------------------------

CREATE TABLE flight_schedule (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flight_number       VARCHAR(8)  NOT NULL,
    origin_code         VARCHAR(3)  NOT NULL REFERENCES airport (code),
    destination_code    VARCHAR(3)  NOT NULL REFERENCES airport (code),
    departure_time      TIME        NOT NULL,             -- UTC time of day
    arrival_time        TIME        NOT NULL,             -- UTC time of day
    -- Derived, never supplied: 1 when arrival_time <= departure_time (overnight).
    arrival_day_offset  INTEGER     NOT NULL DEFAULT 0,
    aircraft_id         BIGINT      NOT NULL REFERENCES aircraft (id),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_schedule_flight_number UNIQUE (flight_number),
    CONSTRAINT chk_schedule_route        CHECK (origin_code <> destination_code),
    CONSTRAINT chk_schedule_day_offset   CHECK (arrival_day_offset BETWEEN 0 AND 1),
    -- PostgreSQL regex; MySQL 8: CHECK (flight_number REGEXP '^[A-Z0-9]{2}[0-9]{1,4}$')
    CONSTRAINT chk_schedule_flight_number CHECK (flight_number ~ '^[A-Z0-9]{2}[0-9]{1,4}$')
);

CREATE TABLE flight_schedule_day (
    schedule_id     BIGINT     NOT NULL REFERENCES flight_schedule (id),
    day_of_week     VARCHAR(9) NOT NULL,
    PRIMARY KEY (schedule_id, day_of_week),
    CONSTRAINT chk_schedule_day CHECK (day_of_week IN
        ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY'))
);

CREATE TABLE flight_instance (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_id         BIGINT      NOT NULL REFERENCES flight_schedule (id),
    -- Route and aircraft are copied from the (immutable) schedule so that
    -- search reads one table through one index.
    flight_number       VARCHAR(8)  NOT NULL,
    origin_code         VARCHAR(3)  NOT NULL REFERENCES airport (code),
    destination_code    VARCHAR(3)  NOT NULL REFERENCES airport (code),
    aircraft_id         BIGINT      NOT NULL REFERENCES aircraft (id),
    flight_date         DATE        NOT NULL,             -- UTC departure date
    departure_at        TIMESTAMPTZ NOT NULL,
    arrival_at          TIMESTAMPTZ NOT NULL,
    total_seats         INTEGER     NOT NULL,
    -- Maintained under the flight row lock: booking/hold decrements,
    -- cancellation/expiry increments.
    available_seats     INTEGER     NOT NULL,
    -- Makes instance generation idempotent (INSERT ... ON CONFLICT DO NOTHING).
    CONSTRAINT uq_instance_schedule_date UNIQUE (schedule_id, flight_date),
    CONSTRAINT chk_instance_seats        CHECK (available_seats BETWEEN 0 AND total_seats),
    CONSTRAINT chk_instance_times        CHECK (arrival_at > departure_at),
    CONSTRAINT chk_instance_flight_number CHECK (flight_number ~ '^[A-Z0-9]{2}[0-9]{1,4}$')
);

-- Serves flight search: WHERE origin_code = ? AND destination_code = ? AND flight_date = ?
CREATE INDEX idx_instance_search
    ON flight_instance (origin_code, destination_code, flight_date);


-- -----------------------------------------------------------------------------
-- Bookings
-- -----------------------------------------------------------------------------

CREATE TABLE booking (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference           VARCHAR(12) NOT NULL,             -- customer-facing PNR
    flight_instance_id  BIGINT      NOT NULL REFERENCES flight_instance (id),
    -- HELD and EXPIRED occur only when airline.seat-hold.enabled = true.
    status              VARCHAR(16) NOT NULL,
    passenger_count     INTEGER     NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL,
    hold_expires_at     TIMESTAMPTZ,                      -- set for bookings created HELD; kept as a record
    cancelled_at        TIMESTAMPTZ,
    -- Serves lookup, confirm and cancel by reference.
    CONSTRAINT uq_booking_reference  UNIQUE (reference),
    CONSTRAINT chk_booking_status    CHECK (status IN ('HELD', 'CONFIRMED', 'CANCELLED', 'EXPIRED')),
    CONSTRAINT chk_booking_count     CHECK (passenger_count > 0),
    -- Exists only as the target of booking_seat's composite foreign key (below).
    CONSTRAINT uq_booking_id_instance UNIQUE (id, flight_instance_id)
);

-- Serves lazy hold expiry: HELD bookings on one instance with hold_expires_at <= now.
CREATE INDEX idx_booking_instance ON booking (flight_instance_id);

CREATE TABLE booking_seat (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id          BIGINT       NOT NULL REFERENCES booking (id),
    -- Copied from the booking because uq_active_seat needs it on this table; the composite
    -- foreign key below guarantees it always equals the booking's flight.
    flight_instance_id  BIGINT       NOT NULL REFERENCES flight_instance (id),
    seat_number         VARCHAR(4)   NOT NULL,            -- e.g. 12A
    passenger_name      VARCHAR(120) NOT NULL,
    status              VARCHAR(16)  NOT NULL,
    created_at          TIMESTAMPTZ  NOT NULL,
    released_at         TIMESTAMPTZ,
    CONSTRAINT chk_booking_seat_status CHECK (status IN ('ACTIVE', 'HELD', 'RELEASED')),
    -- PostgreSQL regex; MySQL 8: CHECK (seat_number REGEXP '^[1-9][0-9]?[A-Z]$')
    CONSTRAINT chk_booking_seat_number CHECK (seat_number ~ '^[1-9][0-9]?[A-Z]$'),
    CONSTRAINT fk_booking_seat_booking_instance
        FOREIGN KEY (booking_id, flight_instance_id) REFERENCES booking (id, flight_instance_id)
);

-- The double-booking guarantee: at most one ACTIVE or HELD row per seat per flight.
-- Also serves the seat map and the availability check
-- (WHERE flight_instance_id = ? AND status IN ('ACTIVE','HELD') [AND seat_number IN (...)]).
--
-- PostgreSQL partial index. MySQL has no partial indexes; the same guarantee there is a
-- nullable column active_seat_key = CONCAT(flight_instance_id, ':', seat_number), set while
-- the seat is ACTIVE or HELD and NULL once RELEASED, with a plain UNIQUE index on it
-- (MySQL unique indexes allow many NULLs).
CREATE UNIQUE INDEX uq_active_seat
    ON booking_seat (flight_instance_id, seat_number)
    WHERE status IN ('ACTIVE', 'HELD');

-- Serves loading a booking's seats (Booking -> BookingSeat collection).
CREATE INDEX idx_booking_seat_booking ON booking_seat (booking_id);
